### ISSUE TITLE
Sample - Hello Character

### ISSUE THREAD

**Issue by chatelao** [tkhamez/swagger-eve-php#1]
Could you add a minimal "hello world", e.g. to dump the information about myself. I don't understand, where I would have to safe the configuration (secrets, callback, etc.).

btw: I really love that this project is based on "OpenAPI-Generator"

**Comment by tkhamez** [comment]
Hello,

This library does not handle EVE SSO.
You can see how this works, for example, at https://github.com/tkhamez/eve-sso-php.

If you would like to have a complete web application example in PHP with EVE SSO, take a look at this example: https://github.com/bravecollective/neucore-connector-boilerplate.
