### ISSUE TITLE
Autoload not found

### ISSUE THREAD

**Issue by carolinebvlt** [tkhamez/swagger-eve-php#3]
Hi, 

Im sorry for this noob issue but i don't find the autoloader or the vendor folder. I see it's in the gitignore so i'm confused... 
What did I miss ? 

Once again, sorry !

**Comment by tkhamez** [comment]
No worries :)

This is a library that you include into your project, which has the autoloader and vendor directory.

This is what you do to create a new project and include it:

```
composer init
composer require tkhamez/swagger-eve-php
```

Then create a PHP file with your code and include `vendor/autoload.php` at the top.

**Comment by tkhamez** [comment]
If you want to change code or write tests for this library you would do:

```
git clone https://github.com/tkhamez/swagger-eve-php.git
cd swagger-eve-php
composer install
```

Then run tests with `vendor/bin/phpunit`.

**Comment by carolinebvlt** [comment]
Thank you very very much !!!
