### ISSUE TITLE
Etag usage?

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [tkhamez/swagger-eve-php#4]
In the documentation there is mention of cache control, but no real info on how to use it. Can you elaborate?

**Comment by tkhamez** [comment]
You mean the docu from CCP? I don't think the generator library has any documentation on how to use a cache.

But it's possible, the library uses the Guzzle http client, which you can configure with a cache middleware, e.g. [kevinrob/guzzle-cache-middleware](https://github.com/Kevinrob/guzzle-cache-middleware).

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Sorry, I thought you implemented it.  The $if_none_match var on the various API methods. The API response should have the etag in the header, but afaik there is no way to access the response headers

**Comment by tkhamez** [comment]
No worries.

There are 2 ways to access the response headers.

1. Use a middleware for the Guzzle client https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html (look for `mapResponse()` on that page for a simple example), that's how the cache library above does it.
2. For each endpoint there are 2 methods, e.g. `AllianceApi::getAlliances()` and `AllianceApi::getAlliancesWithHttpInfo()`, the later returns an array that includes the response code and headers.

Here's how I configure the client that I use for this library: https://github.com/tkhamez/neucore/blob/b3fe86ffa8b63d98cc0c6d1bcb8084b678902efa/backend/src/Factory/HttpClientFactory.php#L79

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Ok, will take a look! Thanks for this library by the way. Its been very helpful.
