### ISSUE TITLE
Authentication Failures

### ISSUE THREAD

**Issue by Proopai** [tkhamez/swagger-eve-php#5]
So Trying to use the eve-sso-php to authenticate I can Grab the token but when I go to pull an Authenticated endpoint with a Valid token it will give a 403.  Do you have any idea why this? I also do not see any kinda Scopes or anything related to this to add into the pulling of the data.

Thank you.

**Comment by tkhamez** [comment]
I can only guess that you are missing the required scope in the token that you use. You have to request all scopes that you want to use in any request when you get the token with eve-sso-php.

**Comment by Proopai** [comment]
No I am passing the Scopes as per your examples.  The token works also without problems when you use it on the ESI page but not any other.

**Comment by tkhamez** [comment]
Can't help you without seeing code.

**Comment by Proopai** [comment]
The Code is your Example code that you have for both projects.

So I didn't think I needed to Add the code here.  ALSO please stop making it as Complete this is not resolved or completed just leave it open for a bit for me to reply that is why I opened a 2nd ticket.

If you want code then here is what I am using for SSO

`

    // Initiate provider object
    // (if you do not provide all optional URLs this will make a request to the metadata URL to
    // get them).
    try {
        $provider = new Eve\Sso\AuthenticationProvider(
            [
                // required
                'clientId'       => $etClientId,
                'clientSecret'   => base64_decode($etSecretKey),
                'redirectUri'    => $etCallback,
        
                // optional
                'urlAuthorize'   => 'https://login.eveonline.com/v2/oauth/authorize',
                'urlAccessToken' => 'https://login.eveonline.com/v2/oauth/token',
                'urlRevoke'      => 'https://login.eveonline.com/v2/oauth/revoke',
                'urlKeySet'      => 'https://login.eveonline.com/oauth/jwks',
                'issuer'         => 'https://login.eveonline.com',
                'urlMetadata'    => 'https://login.eveonline.com/.well-known/oauth-authorization-server',
            ],
        
            // Add all required scopes.
            ['esi-alliances.read_contacts.v1','esi-assets.read_assets.v1','esi-assets.read_corporation_assets.v1','esi-bookmarks.read_character_bookmarks.v1','esi-bookmarks.read_corporation_bookmarks.v1','esi-calendar.read_calendar_events.v1','esi-calendar.respond_calendar_events.v1','esi-characterstats.read.v1','esi-characters.read_agents_research.v1','esi-characters.read_blueprints.v1','esi-characters.read_chat_channels.v1','esi-characters.read_contacts.v1','esi-characters.read_corporation_roles.v1','esi-characters.read_fatigue.v1','esi-characters.read_fw_stats.v1','esi-characters.read_loyalty.v1','esi-characters.read_medals.v1','esi-characters.read_notifications.v1','esi-characters.read_opportunities.v1','esi-characters.read_standings.v1','esi-characters.read_titles.v1','esi-characters.write_contacts.v1','esi-clones.read_clones.v1','esi-clones.read_implants.v1','esi-contracts.read_character_contracts.v1','esi-contracts.read_corporation_contracts.v1','esi-corporations.read_blueprints.v1','esi-corporations.read_contacts.v1','esi-corporations.read_container_logs.v1','esi-corporations.read_corporation_membership.v1','esi-corporations.read_divisions.v1','esi-corporations.read_facilities.v1','esi-corporations.read_fw_stats.v1','esi-corporations.read_medals.v1','esi-corporations.read_standings.v1','esi-corporations.read_starbases.v1','esi-corporations.read_structures.v1','esi-corporations.read_titles.v1','esi-corporations.track_members.v1','esi-fittings.read_fittings.v1','esi-fittings.write_fittings.v1','esi-fleets.read_fleet.v1','esi-fleets.write_fleet.v1','esi-industry.read_character_jobs.v1','esi-industry.read_character_mining.v1','esi-industry.read_corporation_jobs.v1','esi-industry.read_corporation_mining.v1','esi-killmails.read_corporation_killmails.v1','esi-killmails.read_killmails.v1','esi-location.read_location.v1','esi-location.read_online.v1','esi-location.read_ship_type.v1','esi-mail.organize_mail.v1','esi-mail.read_mail.v1','esi-mail.send_mail.v1','esi-markets.read_character_orders.v1','esi-markets.read_corporation_orders.v1','esi-markets.structure_markets.v1','esi-planets.manage_planets.v1','esi-planets.read_customs_offices.v1','esi-search.search_structures.v1','esi-skills.read_skillqueue.v1','esi-skills.read_skills.v1','esi-ui.open_window.v1','esi-ui.write_waypoint.v1','esi-universe.read_structures.v1','esi-wallet.read_character_wallet.v1','esi-wallet.read_corporation_wallet.v1','esi-wallet.read_corporation_wallets.v1','publicData'],
    
            // Optionally use your own HTTP client.
            httpClient: new GuzzleHttp\Client()
        
            // Optionally add a logger to log exception that are caught from libraries
            // (any class implementing Psr\Log\LoggerInterface, the example uses monolog/monolog
            // which is not included in this package).
            // Will add this in later
            // logger: new Monolog\Logger('SSO', [new Monolog\Handler\StreamHandler('/path/to/logfile')])
        );
    } catch (Exception $e) {
        echo $e->getMessage();
    }

    // Optionally disable signature verification.
    // $provider->setSignatureVerification(false);



for the SkillApi Calls



// Configure OAuth2 access token for authorization: evesso
$config = Swagger\Client\Eve\Configuration::getDefaultConfiguration()->setAccessToken($curaccessToken);

$apiInstance = new Swagger\Client\Eve\Api\SkillsApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client(),
    $config
);

$character_id = $eveId; // int | An EVE character ID
$datasource = 'tranquility'; // string | The server name you would like data from
$if_none_match = 'if_none_match_example'; // string | ETag from a previous request. A 304 will be returned if this matches the current ETag
$token = $curaccessToken;

try {
    $result = $apiInstance->getCharactersCharacterIdAttributes($character_id, $datasource, $if_none_match, $token);
    print_r($result);
} catch (Exception $e) {
    echo '<br>Exception when calling SkillsApi->getCharactersCharacterIdAttributes: ', $e->getMessage(), PHP_EOL;
}




And the Token Refresh is the following


// Refreshes access token, if necessary.
$existingToken = new League\OAuth2\Client\Token\AccessToken([
    'refresh_token' => $refreshToken,
    'access_token' => $oldaccessToken,
    'expires' => $expires,
]);
try {
    $token = $provider->refreshAccessToken($existingToken);
} catch (Exception $e) {
    echo $e->getMessage();
}

`

once again all of them are your Examples of how to use your Packages.

**Comment by tkhamez** [comment]
This is not a support forum, that's why I closed the issue.
There is no problem with the library, that's why I wanted to see your code.
Maybe you hit this bug https://github.com/esi/esi-issues/issues/1089.
