### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by Proopai** [tkhamez/swagger-eve-php#6]
I can only guess that you are missing the required scope in the token that you use. You have to request all scopes that you want to use in any request when you get the token with eve-sso-php.

_Originally posted by @tkhamez in https://github.com/tkhamez/swagger-eve-php/issues/5#issuecomment-2167242318_
            

No I am passing the scope as per the Example to create the initial Token.  Even when using that scope in the first pull it doesn't authenticate properly and gives a 403 error.  I am also using the examples for the refresh token.  Now when It requests permissions n the first SSO login it will give the full list of the scope needed so when I go into the Settings for it the full scope is there.

**Comment by tkhamez** [comment]
Don't create a second issue for the same thing please.
